Zadanie: "Mini-Analizator Logów Serwera"
Wyobraź sobie, że serwer generuje tysiące linii logów. Twoim zadaniem jest przetworzenie tych surowych danych, aby dowiedzieć się, co dzieje się z systemem.

Twoje zadania:
ETAP 1: Parsowanie (Transform) Przetwórz tę listę stringów na listę słowników (structured data). Każdy słownik powinien mieć klucze: timestamp, level, message, details. Podpowiedź: Użyj metody .split(" | ").

ETAP 2: Agregacja (Analysis) Stwórz słownik statystyk, który policzy, ile razy wystąpił dany poziom logów (INFO, ERROR, WARNING). Oczekiwany wynik: {'INFO': 3, 'ERROR': 2, 'WARNING': 1}.

ETAP 3: Filtrowanie Wyodrębnij tylko logi o poziomie ERROR do osobnej listy i wyświetl same ich wiadomości oraz szczegóły.

ETAP 4: Unikalność Wypisz listę unikalnych wiadomości (messages), które pojawiły się w logach. Podpowiedź: Użyj typu danych set (zbiór).

In [2]:
raw_logs = [
    "2026-01-17 10:00:01 | INFO | User logged in | user_id: 101",
    "2026-01-17 10:05:22 | ERROR | Connection lost | db_host: 10.0.0.5",
    "2026-01-17 10:07:01 | INFO | File uploaded | file_name: report.pdf",
    "2026-01-17 10:10:00 | WARNING | High CPU usage | load: 85%",
    "2026-01-17 10:15:00 | ERROR | Connection lost | db_host: 10.0.0.5",
    "2026-01-17 10:20:05 | INFO | User logged out | user_id: 101"
]

In [20]:
import pandas as pd


timestamp = []
level = []
message = []
details = []

for row in raw_logs:
    log = row.split(' | ')
    timestamp.append(log[0])
    level.append(log[1])
    message.append(log[2])
    details.append(log[3])


logs_df = pd.DataFrame({'timestamp': timestamp, 'level': level, 'message': message, 'details' :details})
display(logs_df)    
print(logs_df.info())

# Printing number of appearence of particular level
count_info = logs_df['level'].value_counts()
display(count_info)

error_logs = logs_df[logs_df['level'] == 'ERROR']
error_logs = error_logs[['message', 'details']]
display(error_logs)


unique_messages = logs_df['message'].unique()
print(unique_messages)

             timestamp    level          message                details
0  2026-01-17 10:00:01     INFO   User logged in           user_id: 101
1  2026-01-17 10:05:22    ERROR  Connection lost      db_host: 10.0.0.5
2  2026-01-17 10:07:01     INFO    File uploaded  file_name: report.pdf
3  2026-01-17 10:10:00  WARNING   High CPU usage              load: 85%
4  2026-01-17 10:15:00    ERROR  Connection lost      db_host: 10.0.0.5
5  2026-01-17 10:20:05     INFO  User logged out           user_id: 101

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  6 non-null      object
 1   level      6 non-null      object
 2   message    6 non-null      object
 3   details    6 non-null      object
dtypes: object(4)
memory usage: 324.0+ bytes
None

level
INFO       3
ERROR      2
WARNING    1
Name: count, dtype: int64

           message            details
1  Connection lost  db_host: 10.0.0.5
4  Connection lost  db_host: 10.0.0.5

['User logged in' 'Connection lost' 'File uploaded' 'High CPU usage'
 'User logged out']